name: Build

on:
  push:
    branches:
      - main
      - next
      - next-major
      - '[0-9]+.[0-9]+.x'
      - alpha
      - beta
      - feature/*
      - fix/*
  pull_request:
    branches:
      - main
      - next
      - next-major
      - '[0-9]+.[0-9]+.x'
      - alpha
      - beta
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [11, 17, 20]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
      - name: version
        run: ./gradlew -v
      - name: Build
        run: ./gradlew build
